const QUEUED = "QUEUED";
const IN_PROGRESS = "IN_PROGRESS";
const CONCLUDED = "CONCLUDED";

const TIME_CRITICAL = "TIME_CRITICAL"
const NOT_TIME_CRITICAL= "NOT_TIME_CRITICAL"

module.exports = {
  QUEUED,
  IN_PROGRESS,
  CONCLUDED,
  TIME_CRITICAL,
  NOT_TIME_CRITICAL
};
